[server]
port = 8080
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true

[client]
showErrorDetails = true
toolbarMode = "auto"
