[theme]
# Primary accent color for interactive elements
primaryColor = "#0066cc"

# Background color for the main content area
backgroundColor = "#ffffff"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#f0f2f6"

# Color used for almost all text
textColor = "#31333F"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# If false, will attempt to open a browser window on start
headless = false

# Automatically rerun script when files change
runOnSave = true

# Port where the server will listen for browser connections
port = 8501

# Max size, in megabytes, for files uploaded with the file_uploader
maxUploadSize = 200

[browser]
# Whether to send usage statistics to Streamlit
gatherUsageStats = false

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'
level = "info"

[runner]
# Allows you to type --foo bar instead of --foo=bar
magicEnabled = true

# Stops command line from printing exception details
fastReruns = true

[deprecation]
# If false, will show deprecation warnings
showWarningOnDirectExecution = true
