[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[runner]
magicEnabled = true
fastRerenderEnabled = true

[client]
showErrorDetails = true
toolbarMode = "auto"
